name: Deploy Release

on:
  push:
    tags:
    - "v*"

env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Prepare environment
      uses: ./.github/actions/prepare

    - name: Deploy Github
      run: dart run grinder pkg-github-release

    - name: Deploy Github Linux
      run: dart run grinder pkg-github-linux

  deploy-windows:
    name: Deploy (Windows)
    runs-on: windows-latest
    needs: release
    env:
      GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Prepare environment
      uses: ./.github/actions/prepare

    - name: Deploy Github Windows
      run: dart run grinder pkg-github-windows

  deploy-macos:
    name: Deploy (Macos)
    runs-on: macos-latest
    needs: release
    env:
      GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Prepare environment
      uses: ./.github/actions/prepare

    - name: Deploy Github Mac
      run: dart run grinder pkg-github-macos
